// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PersoonPB.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtoDemo {

  /// <summary>Holder for reflection information generated from PersoonPB.proto</summary>
  public static partial class PersoonPBReflection {

    #region Descriptor
    /// <summary>File descriptor for PersoonPB.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PersoonPBReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9QZXJzb29uUEIucHJvdG8iQwoJUGVyc29vblBCEhAKCHZvb3JuYWFtGAEg",
            "ASgJEhIKCmFjaHRlcm5hYW0YAiABKAkSEAoIbGVlZnRpamQYAyABKAVCDKoC",
            "CVByb3RvRGVtb2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoDemo.PersoonPB), global::ProtoDemo.PersoonPB.Parser, new[]{ "Voornaam", "Achternaam", "Leeftijd" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PersoonPB : pb::IMessage<PersoonPB> {
    private static readonly pb::MessageParser<PersoonPB> _parser = new pb::MessageParser<PersoonPB>(() => new PersoonPB());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PersoonPB> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoDemo.PersoonPBReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PersoonPB() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PersoonPB(PersoonPB other) : this() {
      voornaam_ = other.voornaam_;
      achternaam_ = other.achternaam_;
      leeftijd_ = other.leeftijd_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PersoonPB Clone() {
      return new PersoonPB(this);
    }

    /// <summary>Field number for the "voornaam" field.</summary>
    public const int VoornaamFieldNumber = 1;
    private string voornaam_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Voornaam {
      get { return voornaam_; }
      set {
        voornaam_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "achternaam" field.</summary>
    public const int AchternaamFieldNumber = 2;
    private string achternaam_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Achternaam {
      get { return achternaam_; }
      set {
        achternaam_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "leeftijd" field.</summary>
    public const int LeeftijdFieldNumber = 3;
    private int leeftijd_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Leeftijd {
      get { return leeftijd_; }
      set {
        leeftijd_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PersoonPB);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PersoonPB other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Voornaam != other.Voornaam) return false;
      if (Achternaam != other.Achternaam) return false;
      if (Leeftijd != other.Leeftijd) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Voornaam.Length != 0) hash ^= Voornaam.GetHashCode();
      if (Achternaam.Length != 0) hash ^= Achternaam.GetHashCode();
      if (Leeftijd != 0) hash ^= Leeftijd.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Voornaam.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Voornaam);
      }
      if (Achternaam.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Achternaam);
      }
      if (Leeftijd != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Leeftijd);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Voornaam.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Voornaam);
      }
      if (Achternaam.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Achternaam);
      }
      if (Leeftijd != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Leeftijd);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PersoonPB other) {
      if (other == null) {
        return;
      }
      if (other.Voornaam.Length != 0) {
        Voornaam = other.Voornaam;
      }
      if (other.Achternaam.Length != 0) {
        Achternaam = other.Achternaam;
      }
      if (other.Leeftijd != 0) {
        Leeftijd = other.Leeftijd;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Voornaam = input.ReadString();
            break;
          }
          case 18: {
            Achternaam = input.ReadString();
            break;
          }
          case 24: {
            Leeftijd = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
